### ISSUE TITLE
error on back arrow in chrome

### ISSUE THREAD

**Issue by dkwolfe4** [cristovao-trevisan/webpage#2]
There's an issue on Chrome/MacOSX, where if you open your home page, click Engineer picture and then hit the back arrow you get the following stack trace..

index.mjs:133 Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null
    at h (index.mjs:133)
    at Object.d (index.svelte:38)
    at tn (index.mjs:1185)
    at client.1e61207b.js:1
    at index.mjs:633
    at e (index.mjs:18)
    at Array.forEach (<anonymous>)
    at r (index.mjs:24)
    at Q (index.mjs:615)
    at Object.p (client.1e61207b.js:1)

and nothing appears on the page.  Refreshing the page, brings up the "home" page again.

In addition, the console also has the following upon loading:
DevTools failed to parse SourceMap: https://cristovao-trevisan.github.io/webpage/client/client.1e61207b.js.map

**Comment by cristovao-trevisan** [comment]
Thank you for the issue.
It was a problem with the sapper version, updating it fixed the issue.

May I ask, how did you get here? (you can answer me privately if you want)

**Comment by dkwolfe4** [comment]
> It was a problem with the sapper version, updating it fixed the issue.

Verified fix with your demo web page.. repeating the same steps now works correctly.

> May I ask, how did you get here?

Sure, I'm reading all the old Svelte/Sapper Discord postings and you had posted this as an example sometime in the April 1st - June 1st timeframe (sorry.... I've read way too many posts to remember exactly when) and I clicked the link to look at it, saw the web page, and tried it out.
